Add new config to allow customizing the default/relation based prospector/input
canonical/layer-filebeat pull request #90
Opened 2022-03-14 13:49 UTC by verterok

Add `extra_configs_default_input` config option which is a YAML string that will be inserted "as is" in the config file.

The aim for this is to allow other config tweaks not explicitly exposed in config.yaml, e.g:
 - for high load services, on a initial deploy set `tail_files: true` in order to avoid pushing a *lot* of events that the graylog/logstash/elasticsearch might not be able to handle
 -  to add python multiline support: 
     ```
    multiline:
      pattern: "^([0-9]{4}-[0-9]{2}-[0-9]{2}|[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3})"
      negate: true
      match: after
    ```

2023-03-22 07:49 UTC, Pjack commented
@verterok May I know more details about
- Where does this requirement come from?
- What is the mandatory requirements/features we need? 
Thanks!

2023-07-11 02:59 UTC, jneo8 requested changes
- Unit test is required
- Do you think we can add a simple check for the `extra_configs_default_input` input to avoid we break the config?

2023-08-21 20:15 UTC, gtato commented
What happened to this PR? I am also interested in it (Commercial Systems team), especially on the multi line support.

2023-08-21 20:29 UTC, verterok commented
Hi,

@jneo8 I think we could check if its valid YAML, beyond that it might be too complex and could be a re-implementation of the filebeat config parser.
sounds reasonable to check for valid YAML?

@gtato I was not able to work on this, we are currently (since the PR was created actually) using a build of the charm with the patch applied.

Regards

2023-09-05 02:04 UTC, jneo8 commented
> I think we could check if its valid YAML, beyond that it might be too complex and could be a re-implementation of the filebeat config parser.
> sounds reasonable to check for valid YAML?

Yes, check if it's valid YAML before render the template will be nice.
Also a simple unit test to check the template works as what we expect is required.

2023-10-12 09:42 UTC, gtato commented
Hi @verterok, I would totally understand if this is at the bottom of your todo list, but just wanted to have an idea for when we could have this on charmhub?

2023-10-19 17:34 UTC, shanepelletier commented
@jneo8

> Also a simple unit test to check the template works as what we expect is required.

I'm currently working on this, but I can't figure out how to locally run the tests using `amulet`. To workaround this, I was just going to write a simple unittest for the `render_filebeat_template()` function, but unfortunately that function requires `elasticbeats` which AFAIK is only shipped as part of `layer-beats-base` and I can't just mock out the import since the template rendering requires a function from the `elasticbeats` module. So, my question is: **how are tests actually being ran for `layer-filebeat`**?

2023-10-20 20:49 UTC, verterok commented
Closing this in favor of #106

2023-10-20 20:49 UTC, closed without merging